apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-fixed-count-job
spec:
  template:
    metadata:
      name: parallel-fixed-count-pod
    spec:
      containers:
      - name: parallel-fixed-count-container
        image: alpine
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Starting the script";
            echo "Waiting for 5 seconds...";
            sleep 5;
            echo "Wait time completed.";
      restartPolicy: Never
  completions: 6
  parallelism: 3