apiVersion: batch/v1
kind: CronJob
metadata:
  name: basic-cronjob
  namespace: example-kubernetes
spec:
  schedule: "*/1 * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: non-parallel-container
            image: alpine
            command: ["/bin/sh", "-c"]
            args:
              - |
                echo "Starting the script";
                echo "Waiting for 5 seconds...";
                sleep 5;
                echo "Wait time completed.";
          restartPolicy: Never