apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: example-kubernetes
  labels:
    app: service-a
spec:
  selector:
    matchLabels:
      app: service-a
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: maiconghidolin/net-kubernetes:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
          # - name: ServiceName
          #   value: "A"
          # - name: ApiPathBase
          #   value: "service-a"
          - name: PodName
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: PodIP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
        - name: appsettings-volume
          mountPath: /src/appsettings.json
          subPath: appsettings.json
      volumes:
      - name: appsettings-volume
        configMap:
          name: service-a
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: example-kubernetes
  labels:
    app: service-a
spec:
  selector:
    app: service-a
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-a
  namespace: example-kubernetes
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "*",
      "ServiceName": "A with configmap",
      "ApiPathBase": "service-a",
    }