apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: example-kubernetes
  labels:
    app: service-b
spec:
  selector:
    matchLabels:
      app: service-b
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: maiconghidolin/net-kubernetes:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
          - name: ServiceName
            value: "B"
          - name: API_PATH_BASE
            value: "service-b"
          - name: PodName
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: PodIP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: example-kubernetes
  labels:
    app: service-b
spec:
  selector:
    app: service-b
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080