apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-deploy
  namespace: kustomize-example
  labels:
    app: kustomize-deploy
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: kustomize-container
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"