apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:     
      containers:
      - name: server
        image: maiconghidolin/net-healthchecks:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        command:
          - sh
          - -c
          - |
            if [ ! -f /app/Resources/text.txt ]; then
              mkdir -p /app/Resources && echo "Response Ok" > /app/Resources/text.txt
            fi
            dotnet HealthChecks.dll
        readinessProbe:
          httpGet:
            path: /home
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /home
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 4
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080